spring:
  application:
    name: certificado-backend
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:h2:mem:certificado_db}
    driverClassName: ${SPRING_DATASOURCE_DRIVER_CLASS_NAME:org.h2.Driver}
    username: ${SPRING_DATASOURCE_USERNAME:sa}
    password: ${SPRING_DATASOURCE_PASSWORD:}
  jpa:
    database-platform: ${SPRING_JPA_DATABASE_PLATFORM:org.hibernate.dialect.H2Dialect}
    hibernate:
      ddl-auto: update
    show-sql: true
  h2:
    console:
      enabled: true
      path: /h2-console
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

app:
  jwt:
    secret: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
    expirationMs: 86400000 # 24 horas
  file:
    upload-dir: temp/uploads

resend:
  # Tenta buscar a variável de ambiente (Render), se não achar, usa a chave fornecida para rodar localmente
  api-key: ${RESEND_API_KEY:re_PmGBg8om_7qWdKC97HPjFjofPYabYuMks}
